name = "my-test-function-name"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "my-test-function-name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "my-test-function-name.wasm"
command = "npm run build:release"
